---
title: "R Notebook"
output: html_notebook
---




```{r}
setwd("C://Users/Anahid/Desktop/Howler/R-mpa")
```

```{r}
library(dplyr)
```
```{r}
###filter for genus level

data <- read.table("edited_mpa4-merged-KM.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)
genus_data <- data %>% filter(str_detect(clade,"g__"))  %>% filter(!str_detect(clade,"s__")) %>% mutate(clade = sub(".*g__", "", clade)) 

genus_data[, 1] <- gsub("[;:]", "_", genus_data[, 1])
colnames(genus_data) <- gsub("\\.", "-", colnames(genus_data))

genus_data


# Write the filtered data to a new tab-separated file
output_file <- "new-filtered_genus.txt"
write.table(genus_data, file = output_file, sep = "\t", row.names = FALSE, quote = FALSE)

cat("Filtered species-level data has been written to", output_file, "\n")
```

```{r}
### filter for species level

data <- read.table("edited_mpa4-merged-KM.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)
species_data <- data %>% filter(str_detect(clade,"s__"))  %>% 
  filter(!str_detect(clade,"t__")) %>% 
  mutate(clade = sub(".*s__", "", clade))  %>%
  filter(clade != "")

species_data[, 1] <- gsub("[;:]", "_", species_data[, 1])
colnames(species_data) <- gsub("\\.", "-", colnames(species_data))

species_data


# Write the filtered data to a new tab-separated file
output_file <- "new-filtered_species.txt"
write.table(species_data, file = output_file, sep = "\t", row.names = FALSE, quote = FALSE)

cat("Filtered species-level data has been written to", output_file, "\n")
```


